// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-drops.ts
import { createClient } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
var list_drops_default = defineTool({
  name: "list_drops",
  title: "List drops",
  description: "List public drops (creative playable art & experiments) from bryanlauwk.fun.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(20).describe("Max drops to return."),
    tag: z.string().optional().describe("Optional tag filter (exact match).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ limit, tag }) => {
    const url = process.env.SUPABASE_URL;
    const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
    const supabase = createClient(url, key, { auth: { persistSession: false } });
    let query = supabase.from("projects").select("title, description, href, tag, color, updated_at").eq("is_visible", true).order("display_order", { ascending: true }).limit(limit);
    if (tag) query = query.eq("tag", tag);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { drops: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-drop.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
var get_drop_default = defineTool2({
  name: "get_drop",
  title: "Get drop",
  description: "Fetch a single visible drop by its title (case-insensitive contains match).",
  inputSchema: {
    title: z2.string().min(1).describe("Full or partial drop title.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ title }) => {
    const url = process.env.SUPABASE_URL;
    const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
    const supabase = createClient2(url, key, { auth: { persistSession: false } });
    const { data, error } = await supabase.from("projects").select("title, description, href, tag, color, updated_at").eq("is_visible", true).ilike("title", `%${title}%`).limit(1).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: `No drop found matching "${title}".` }] };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { drop: data }
    };
  }
});

// src/lib/mcp/tools/submit-message.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
var submit_message_default = defineTool3({
  name: "submit_message",
  title: "Submit guest book message",
  description: "Send a public feedback or idea message to bryanlauwk.fun's guest book. For private/sponsorship inquiries include an email.",
  inputSchema: {
    name: z3.string().trim().min(1).max(50).describe("Sender name (1-50 chars)."),
    message: z3.string().trim().min(1).max(1e3).describe("Message body (1-1000 chars)."),
    category: z3.enum(["feedback", "idea", "sponsorship", "private"]).default("feedback").describe("Message category."),
    email: z3.string().email().max(255).optional().describe("Required for private/sponsorship.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: true },
  handler: async ({ name, message, category, email }) => {
    if ((category === "private" || category === "sponsorship") && !email) {
      return {
        content: [{ type: "text", text: "Email is required for private and sponsorship messages." }],
        isError: true
      };
    }
    const url = process.env.SUPABASE_URL;
    const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
    const supabase = createClient3(url, serviceKey, { auth: { persistSession: false } });
    const { error } = await supabase.from("guest_book").insert([
      { name, message, category, email: email ?? null }
    ]);
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    return { content: [{ type: "text", text: "Message received. Thanks for writing in." }] };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ywirnyuvvpenzajaajkg";
var mcp_default = defineMcp({
  name: "bryanlauwk-fun-mcp",
  title: "bryanlauwk.fun",
  version: "0.1.0",
  instructions: "Tools for bryanlauwk.fun \u2014 a collection of playable art and creative web experiments. Use `list_drops` to browse drops, `get_drop` to fetch details of a specific drop, and `submit_message` to send feedback, ideas, or sponsorship inquiries.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_drops_default, get_drop_default, submit_message_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
